<?php

/**
 * @file
 * Provide scroll to top link.
 */

/**
 * Implementation of hook_init() -> in Drupal 8 noemt dit nu precprocess.
 */
function scroll_to_top_preprocess_page(&$variables) {

  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $admin_theme = \Drupal::config('system.theme')->get('admin');

  $config = \Drupal::config('scroll_to_top.settings');

 if ($config->get('scroll_to_top_enable_admin_theme')==TRUE || ($config->get('scroll_to_top_enable_admin_theme')==FALSE && ($theme != $admin_theme))) {
 
  $variables['#attached']['library'][] = 'scroll_to_top/scroll_to_top'
  
  //building the css style
  $position = "";
  // Button position
 if ($config->get('scroll_to_top_position')== 1) {
  $position = "#back-top { right:40px; }";
  }
 if ($config->get('scroll_to_top_position')== 3) {
  $position = "#back-top { left:50%;margin:0px;}";
  }
  // Display label
 if ($config->get('scroll_to_top_display_text')==FALSE) {
  $display = "span#link {display : none;}";
  } 
 else {
  $display = "";
  }
  // background color on hover
 $bgcolor = "#back-top span#button { background-color: " . $config->get('scroll_to_top_bg_color_out', '#CCCCCC') . ";}";
 $bgcolor .= " #back-top span#button:hover {opacity:1;filter:alpha(opacity = 1);background-color: " . $config->get('scroll_to_top_bg_color_hover', '#777777') . ";}";
 $css = $position;
 $css .= $bgcolor;
 $css .= $display;
 
 $variables['#attached']['js'][]=array('type' => 'setting', 'data'=>array('label'=>t($config->get('scroll_to_top_label))));

 $variables['#attached']['css'][]array('data'=>$css,'type'=>'inline');
 }
}

 /**
 * Implements hook_menu().
 */
function scroll_to_top_menu() {
  $items = array();

  $items['admin/config/user-interface/scrolltotop'] = array(
    'title' => 'Scroll to top',
    'description' => 'Scroll To Top settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scroll_to_top_settings'),
    'access arguments' => array('administer scroll to top'),
    'file' => 'scroll_to_top.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function scroll_to_top_permission() {
  return array(
    'administer scroll to top' => array(
      'title' => t('Administer scroll to top'),
      'description' => t('Perform administration tasks for scroll to top.'),
    ),
  );
}